version: "2"
services:
  only_onece:
    container_name: only_onece
    stdin_open: true
    tty: true
    build: .
    command: /root/.bun/bin/bun run http.ts &
    volumes:
      - .:/root/develop
    working_dir: /root/develop
    ports:
      - 3000:3000